### PR TITLE
Added another TAFFETAS2 model

### PR DESCRIPTION
**Pull request by molusk**
Updated acova.js to include variations in the annouced model from older heaters.

### CODE REVIEW

**Comment by ullrik** [comment]
Hello,
I just bought and added a TAFFETAS2 model (D1.00P1.02Z1.00).
I have the impression that the local_temperature value goes up the value selected at the level of the display of the radiator and not the value of the thermostat probe. Do you confirm?

**Comment by molusk** [comment]
Yes, I did not find any way to get probe value...

**Comment by molusk** [comment]
I just checked my custom converter for this heater, I added a few things if you are interested : ability to control unoccupied set-point (but only from z2m UI), occupancy reporting (when triggered it stays on for 2 hours but it is still useful to have an unnoticeable motion sensor in each room for alarmo).

I was not able to get the right names for the hvac modes : heat => frost protection, no eco mode (it would just disable the motion sensor and use unoccupied set-point). It is frustrating as it is the only thing that worked better with domoticz...

I did not try to get reports from the window open sensor but it seems to be a simple binary sensor. I don't know how accurate it may be.

**Comment by molusk** [comment]
You triggered me, I pushed my custom converter and made a pull request to Koenkk ;)
https://github.com/Koenkk/zigbee-herdsman-converters/pull/5773

**Comment by ullrik** [comment]
Hello, I'm back after a long absence.
I updated to version [1.32.2] of zigbee2mqtt, but I don't see the same as in your modification https://github.com/Koenkk/zigbee-herdsman-converters/pull/5773/files does that mean it was denied or backtracked?

**Comment by molusk** [comment]
Hello,
I just disabled my custom converter to confirm, everything is ok for me with version 1.32.2 of z2m.
Maybe you were looking for the stripped version of the model definition ?
I had to put back the strange trailing characters : https://github.com/Koenkk/zigbee-herdsman-converters/pull/5815

Anyway, I noticed also an error in the acova.js file, someone added a Taffetas2 model in the Percale2 definition. If you have a TAFFETAS2 D1.00P1.03Z1.00, it may get Percale2 configuration which is a subset of Taffetas2 configuration (i.e. none of my late additions are available). I will look for the PR which introduced this modification and check with the owner if he wants me to do the modification or if he does it.

**Pull request merged**
